/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.EventQueue;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author XIZUTH
 */
public class Consultar extends javax.swing.JPanel {

    /**
     * Creates new form Eliminar
     */
    public Consultar() {
        initComponents();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logo.png"))); // NOI18N
        jLabel8.setText("Logo");

        BaseDeDatos db = new BaseDeDatos();

        Vector resultados = Variables.BD.getEmpleados();
        Vector columna = new Vector();

        columna.add("ID");
        columna.add("Nombre");
        columna.add("Apellido Paterno");
        columna.add("Apellido Materno");
        columna.add("Departamento");
        columna.add("Salario");
        columna.add("Correo");
        columna.add("Foto");
        jTable1.setModel(
            new javax.swing.table.DefaultTableModel(
                resultados,columna)
        );
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Empleados:");

        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel1))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton2)
                                .addComponent(jButton4)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
        
        RegistroD registro = new RegistroD(null, true);
        
        registro.setVisible(true);
        
        actualizarTabla();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            
            int i = jTable1.getSelectedRow(); //obtenemos el que seleccionamos
            Vector result = Variables.BD.getEmpleados(); //crea el objeto Base de datos
            //se usa el try por ke si no se selecciona ningun registro marca una excepcion
            Vector registro = (Vector) result.get(i); //aqui pondra la posicion del seleccionado en la tabla
        
            DialogoModificar regist = new DialogoModificar(null, true,registro);//apartir del constructor hecho, se le pasa 
                                                                    //el vector para que carge los valores anteriores
            Variables.dModificar = regist;
            regist.setVisible(true);
            actualizarTabla();
            
        }catch(ArrayIndexOutOfBoundsException e){
            
            JOptionPane.showMessageDialog(this, "Empleado no seleccionado");
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        int []i = jTable1.getSelectedRows(); //obtenemos el que seleccionamos
        Vector result = Variables.BD.getEmpleados(); //crea el objeto Base de datos
        //se usa el try por ke si no se selecciona ningun registro marca una excepcion

        Vector <Integer> ids = new Vector <Integer>(); //Vector de ids para eliminar
        for (int valor :i){ //obtener ids que se van a eliminar
                  Vector registro = (Vector) result.get(valor); //aqui pondra la posicion del seleccionado en la tabla
                  ids.add((Integer)registro.get(0));
        }//fin del for mejorado

        if (Variables.BD.eliminarEmpleado(ids) ){  //se hace uso del metodo para eliminar los seleccionador
                actualizarTabla();
                JOptionPane.showMessageDialog(null, "Registro(s) eliminado(s).");
            }
        else
            JOptionPane.showMessageDialog(null, "Error al eliminar. ");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:  ************** BUSCAR
         jTable1 = new javax.swing.JTable();
         String busqueda = jTextField1.getText();
         
         if(busqueda.compareTo("") != 0 ){ //si no escribe nada en el cuadro de texto no buscara nada
            Vector resultados = Variables.BD.buscarEmpleados(busqueda);
            Vector columna = new Vector();

        columna.add("ID");
        columna.add("Nombre");
        columna.add("Apellido Paterno");
        columna.add("Apellido Materno");
        columna.add("Departamento");
        columna.add("Salario");
        columna.add("Correo");
        columna.add("Foto");
        jTable1.setModel(new javax.swing.table.DefaultTableModel(resultados,columna) );
         }
         else { actualizarTabla();} //solo actualizara la tabla de nuevo y resetea la busqueda
        jScrollPane1.setViewportView(jTable1);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        jButton3ActionPerformed(evt);
    }//GEN-LAST:event_jTextField1ActionPerformed

    public void actualizarTabla(){
        
        jTable1 = new javax.swing.JTable();
        Vector resultados = Variables.BD.getEmpleados();
        Vector columna = new Vector();

        columna.add("ID");
        columna.add("Nombre");
        columna.add("Apellido Paterno");
        columna.add("Apellido Materno");
        columna.add("Departamento");
        columna.add("Salario");
        columna.add("Correo");
        columna.add("Foto");
        jTable1.setModel(new javax.swing.table.DefaultTableModel(resultados,columna) );

        jScrollPane1.setViewportView(jTable1);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
